### PR TITLE
Latest Upstream (new SDK) with our changes #WIP

### PR DESCRIPTION
**Pull request by naveedhd**
In this branch, I have placed our changes (nodelet, re-initializing driver, publish fixes) on top of latest upstream branch. 

This is supposed to be used with new RPLidars (A2) but works also with current ones.

One thing to note is that starting motor and few other things are handled differently in new SDK, so we need to make sure they are compatible with out re-initializing driver handling. I have tested it with new rplidar but may produce issues while `real` testing.

### CODE REVIEW

**Comment by stonier** [comment]
Q) How did you go with the disabling of the motors when the nodelets shutdown? Did you try the small sleep to enable them to fire off their publishers?

**Comment by stonier** [comment]
Is this actually including the new driver? There are some parts of the sdk that seem quite old....e.g. `sdk/src/rplidar_driver.cpp` is different to here
- https://github.com/robopeak/rplidar_ros/blob/master/sdk/src/rplidar_driver.cpp#L61
- https://github.com/yujinrobot/rplidar_ros/blob/gocart_21/sdk/src/rplidar_driver.cpp#L61

**Comment by stonier** [comment]
Ok, above change was made by us (@bit-pirate). Having a look at this mess, I would like to zag on this and go a slightly different direction. Let's talk about this when you're in.

**Comment by naveedhd** [comment]
@stonier I tried small sleep in destructor but it did not solve the problem.

**Comment by stonier** [comment]
Closing this, please refer to #20

**Pull request closed without merging**
