### PR TITLE
diagnostics in rplidar_driver

### PR DESCRIPTION
**Pull request by naveedhd**
Adds diagnostic messages to RPLidar Driver.

The KeyValue pair contains counter for how many times driver has encountered failure, timeout and bad health status along with elapsed time since node started.

### CODE REVIEW

**Comment by naveedhd** [comment]
Related [PR](https://bitbucket.org/yujinrobot/gopher/pull-requests/148/gopher_robot-diagnostics-in-rplidar-driver/diff)

**Comment by stonier** [comment]
Would be good to have this do more than just a count. From a glance, looking at the count doesn't actually tell whether its bad or good - it could be a count of 5 over the course of 10 days (ok) or it could be a count of 5 over the course of 30 mins (bad).

**Comment by naveedhd** [comment]
It has `elapsed_time` also by which we can have idea of frequency of error.

**Comment by stonier** [comment]
Same problem - still probably not a great indicator if the robots are up for a significant amount of time. Could you make it work over a reasonably sized moving window?

**Comment by naveedhd** [comment]
Right! Yeah sure.

**Comment by stonier** [comment]
You could leave the elapsed time and counters as is, just dump timestamps for each type into a deque, pop them off the front if they get too old and then put that 'rate' in the counter view alongside the old values.

**Comment by naveedhd** [comment]
the 'rate of error` is now in.

**Comment by stonier** [comment]
```
     _  _(o)_(o)_  _
   ._\`:_ F S M _:' \_,
       / (`---'\ `-.
    ,-`  _)    (_,
```

**Pull request merged**
